def build(bld):
	sources = [
		"ft_bzero.c",
		"ft_calloc.c",
		"ft_memchr.c",
		"ft_memcmp.c",
		"ft_memcpy.c",
		"ft_memmove.c",
		"ft_memset.c"
	]
	lftmem = bld.stlib(
		source		= sources,
		features	= "c cstlib",
		target		= "ftmem",
		includes	= bld.env.INCLUDES_ROOT
	)
	lftmem.post()
