def build(bld):
	sources = [
		"is_charset.c",
		"is_chartype.c",
		"is_valid.c",
		"str_comparison.c"
	]
	lftstrchk = bld.stlib(
		source		= sources,
		features	= "c cstlib",
		target		= "ftstrchk",
		includes	= bld.env.INCLUDES_ROOT
	)
	lftstrchk.post()
